version: "2.3"

services:
    api:
        build: bodypix/
        runtime: nvidia
        ports:
            - 9000:9000
        command: node /src/app.js
    fakecam:
        build: fakecam/
        ports:
            - 8080:8080
        devices:
            - /dev/video1:/dev/video1
            - /dev/video20:/dev/video20
        command: python -u main.py